// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Areas.Admins.Models;

public partial class TagClass
{
    public int TagClassId { get; set; }

    public string TagClassName { get; set; }

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}