// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Areas.Candidates.Models;

public partial class ResumeOpeningRecord
{
    public int ResumeOpeningRecordID { get; set; }

    public int? ResumeID { get; set; }

    public int? OpeningID { get; set; }

    public int CompanyID { get; set; }

    public string CompanyName { get; set; }

    public string OpeningTitle { get; set; }

    public DateOnly? ApplyDate { get; set; }

    public bool LikeYN { get; set; }

    public bool InterviewYN { get; set; }

    public bool HireYN { get; set; }

    public virtual Opening Opening { get; set; }

    public virtual Resume Resume { get; set; }
}