// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Areas.Candidates.Models;

public partial class TitleCategory
{
    public int TitleCategoryId { get; set; }

    public string TitleCategoryName { get; set; }

    public virtual ICollection<TitleClass> TitleClasses { get; set; } = new List<TitleClass>();
}