// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class Admin
{
    public int AdminId { get; set; }

    public int PersonnelCode { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public int? Authority { get; set; }

    public virtual ICollection<CandidateLetter> CandidateLetters { get; set; } = new List<CandidateLetter>();

    public virtual ICollection<CompanyApproval> CompanyApprovals { get; set; } = new List<CompanyApproval>();

    public virtual ICollection<CompanyLetter> CompanyLetters { get; set; } = new List<CompanyLetter>();
}