// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class CandidateOpeningRecord
{
    public int CandidateOpeningRecordId { get; set; }

    public int? CandidateId { get; set; }

    public int? OpeningId { get; set; }

    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string OpeningTitle { get; set; }

    public int? ResumeId { get; set; }

    public DateOnly? ApplyDate { get; set; }

    public bool LikeYn { get; set; }

    public bool InterviewYn { get; set; }

    public bool HireYn { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual Opening Opening { get; set; }
}