// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class CompanyApproval
{
    public int CompanyId { get; set; }

    public int AdminId { get; set; }

    public bool Status { get; set; }

    public DateTime Date { get; set; }

    public virtual Admin Admin { get; set; }

    public virtual Company Company { get; set; }
}