// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class CompanyOrder
{
    public int OrderId { get; set; }

    public int? CompanyId { get; set; }

    public int? PlanId { get; set; }

    public string CompanyName { get; set; }

    public int Guinumber { get; set; }

    public string PlanTitle { get; set; }

    public DateTime OrderDate { get; set; }

    public virtual Company Company { get; set; }

    public virtual PricingPlan Plan { get; set; }
}