// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class CompanyResumeRecord
{
    public int CompanyId { get; set; }

    public int ResumeId { get; set; }

    public bool LikeYn { get; set; }

    public bool? InterviewYn { get; set; }

    public bool? HireYn { get; set; }

    public virtual Company Company { get; set; }

    public virtual Resume Resume { get; set; }
}