// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class CompanyClass
{
    public string CompanyClassId { get; set; }

    public string CompanyCategoryId { get; set; }

    public string CompanyClassName { get; set; }

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual CompanyCategory CompanyCategory { get; set; }
}