// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class OpeningTag
{
    public int OpeningId { get; set; }

    public int TagId { get; set; }

    public bool TagStatus { get; set; }

    public virtual Opening Opening { get; set; }

    public virtual Tag Tag { get; set; }
}