// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class OpeningTag
{
    public int OpeningID { get; set; }

    public int TagID { get; set; }
}