// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class ResumeTag
{
    public int ResumeId { get; set; }

    public int TagId { get; set; }

    public bool TagStatus { get; set; }

    public virtual Resume Resume { get; set; }

    public virtual Tag Tag { get; set; }
}