// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class Resume
{
    public int ResumeId { get; set; }

    public int CandidateId { get; set; }

    public string Title { get; set; }

    public string TitleClass { get; set; }

    public string Intro { get; set; }

    public string Autobiography { get; set; }

    public string WorkExperience { get; set; }

    public byte[] Certification { get; set; }

    public string Time { get; set; }

    public string Address { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual ICollection<CompanyResumeRecord> CompanyResumeRecords { get; set; } = new List<CompanyResumeRecord>();

    public virtual ICollection<ResumeTag> ResumeTags { get; set; } = new List<ResumeTag>();
}