// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public int TagClassId { get; set; }

    public virtual ICollection<OpeningTag> OpeningTags { get; set; } = new List<OpeningTag>();

    public virtual ICollection<ResumeTag> ResumeTags { get; set; } = new List<ResumeTag>();

    public virtual TagClass TagClass { get; set; }
}