// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Models;

public partial class TagClasses
{
    public int TagClassID { get; set; }

    public string TagClass { get; set; }

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}