// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Areas.Companies.Models;

public partial class Company
{
    public int CompanyID { get; set; }

    public int GUINumber { get; set; }

    public string Password { get; set; }

    public string CompanyName { get; set; }

    public string Address { get; set; }

    public string Intro { get; set; }

    public string Benefits { get; set; }

    public byte[] Picture { get; set; }

    public string ContactName { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public bool Status { get; set; }

    public DateTime Date { get; set; }
}