// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobHunting.Areas.Companies.Models;

public partial class CompanyCategory
{
    public string CompanyCategoryId { get; set; }

    public string CompanyCategoryName { get; set; }

    public virtual ICollection<CompanyClass> CompanyClasses { get; set; } = new List<CompanyClass>();
}